from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class DashboardSchematicTests(unittest.TestCase):
    def test_schematic_contains_every_energy_component(self) -> None:
        dashboard = (ROOT / "templates" / "index.html").read_text(encoding="utf-8")

        for component_id in (
            "diagramNodePv",
            "diagramNodeSolix",
            "diagramNodeGrid",
            "diagramNodeHome",
            "diagramNodeOther",
            "diagramNodePlug",
            "diagramNodeAudi",
        ):
            self.assertIn(f'id="{component_id}"', dashboard)

        self.assertIn("Energiefluss im Gesamtsystem", dashboard)
        self.assertIn("style.css?v=20260906-129", dashboard)
        self.assertIn("house.js?v=20260906-129", dashboard)
        self.assertIn("app.js?v=20260821-96", dashboard)
        self.assertIn('type="module" src="/static/house.js', dashboard)
        self.assertIn("three@0.185.1", dashboard)

    def test_schematic_is_wired_to_live_values(self) -> None:
        script = (ROOT / "static" / "app.js").read_text(encoding="utf-8")

        for live_value in (
            "battery_discharge_power",
            "system_output_power",
            "smartPlug.power_w",
            "audi.battery_percent",
            "remaining_charging_minutes",
        ):
            self.assertIn(live_value, script)

        self.assertIn('setDiagramLink("diagramLinkAudi", charging)', script)
        self.assertNotIn('getElementById("flowPV")', script)

    def test_virtual_house_is_touch_enabled_and_uses_live_data(self) -> None:
        dashboard = (ROOT / "templates" / "index.html").read_text(encoding="utf-8")
        script = (ROOT / "static" / "house.js").read_text(encoding="utf-8")
        stylesheet = (ROOT / "static" / "style.css").read_text(encoding="utf-8")

        self.assertIn('id="houseCanvas"', dashboard)
        self.assertIn('id="houseReset"', dashboard)
        self.assertIn('id="builderTouchBuild"', dashboard)
        self.assertIn('id="builderTouchCamera"', dashboard)
        self.assertIn('addEventListener("pointermove"', script)
        self.assertIn('addEventListener("wheel"', script)
        self.assertIn("pointerDistance", script)
        self.assertIn("cameraNavigation", script)
        self.assertIn("Kamera aktiv: mit einem Finger drehen", script)
        self.assertIn('addEventListener("solix-dashboard-data"', script)
        self.assertIn('label: "AUDI Q3"', script)
        self.assertIn("WebGLRenderer", script)
        self.assertIn("MeshPhysicalMaterial", script)
        self.assertIn("shadowMap.enabled", script)
        self.assertNotIn('label: "SMART PLUG"', script)
        self.assertNotIn('label: "HAUSGERÄTE"', script)
        self.assertIn('solix["pv" + number]', script)
        self.assertIn('createFlow(panel.id', script)
        self.assertIn('className = "house-string-label"', script)
        self.assertIn('createDoor(house, [3.285, 3.58, 4.10]', script)
        self.assertIn('createDoor(house, [3.285, 3.58, 1.45]', script)
        self.assertIn('createWindow(house, [3.285, 3.66, 0.18]', script)
        self.assertIn('createDoor(house, [3.285, 3.58, -4.06]', script)
        self.assertIn('createFrontWoodDoor(house, [3.30, 1.35, -3.15]', script)
        self.assertIn('createDoor(house, [3.30, 1.35, -4.30]', script)
        self.assertIn('createDoor(house, [-3.30, 1.34, -3.55]', script)
        self.assertIn('createDoor(house, [-3.285, 3.58, -3.62]', script)
        self.assertIn("function createJulietGuard", script)
        self.assertIn("function createWoodDoorWithCanopy", script)
        self.assertIn("function createFrontWoodDoor", script)
        self.assertIn('createWoodDoorWithCanopy(house, [-3.30, 1.34, 1.80]', script)
        self.assertIn('INDIVIDUAL_OPENINGS.door.rearDecorative, [1.56, 1.92]', script)
        self.assertIn('path: "/static/textures/house/window-atlas-individual-v3.jpg"', script)
        self.assertIn('path: "/static/textures/house/door-atlas-individual-v3.jpg"', script)
        self.assertIn('path: "/static/textures/house/garage-atlas-clean-v3.jpg"', script)
        self.assertIn('loadImageTexture("/static/textures/house/garage-shingles-clean-v3.jpg"', script)
        self.assertIn("cleanAsset: true", script)
        self.assertIn("if (cleanAsset)", script)
        self.assertTrue((ROOT / "static" / "textures" / "house" / "window-atlas-individual-v3.jpg").is_file())
        self.assertTrue((ROOT / "static" / "textures" / "house" / "door-atlas-individual-v3.jpg").is_file())
        self.assertTrue((ROOT / "static" / "textures" / "house" / "garage-atlas-clean-v3.jpg").is_file())
        self.assertTrue((ROOT / "static" / "textures" / "house" / "garage-shingles-clean-v3.jpg").is_file())
        self.assertIn("Gartenfassade aus IMG_7397", script)
        self.assertIn("[0.16, 4.90, 2.45]", script)
        self.assertIn("[5.22, 1.02, INDIVIDUAL_OPENINGS.window.brownDoubleCurtain]", script)
        self.assertIn("const facadeX = z > 4.5 ? -3.39 : -3.30", script)
        self.assertIn('createWindow(house, [-3.39, 1.48, 5.08]', script)
        self.assertIn('THREE.MathUtils.degToRad(-60)', script)
        self.assertIn('addBox(pool, [1.02, 0.15, 4.05], deckWood, [-1.82, 0.91, 0]', script)
        self.assertIn("pool.position.set(-7.19, 0, -5.92)", script)
        self.assertIn("Begehbare Holzumrandung", script)
        self.assertIn("const PROPERTY_BOUNDARY = [", script)
        self.assertIn("function addHorizontalPolygon", script)
        self.assertIn("function createFencePath", script)
        self.assertIn("function createDeciduousTree", script)
        self.assertIn("[7.82, -18.80]", script)
        self.assertIn("[13.20, -20.20]", script)
        self.assertIn("function createGoldfishPond", script)
        self.assertIn("function animatePondFish", script)
        self.assertIn("pond.position.set(-4.85, 0.035, 14.78)", script)
        self.assertIn("[-6.82, 14.58, 0.72]", script)
        self.assertIn("const rearFenceJunction = [-11.50, -6.42]", script)
        self.assertIn("const AUDI_SIDE_FENCE_X = 7.20", script)
        self.assertNotIn("const hedge =", script)
        self.assertNotIn("createDeciduousTree(-4.72, -1.25, 0.68)", script)
        self.assertIn("[3.2, 0.07, 13.2]", script)
        self.assertIn("yetiSlot.position.set(0, 0.02, 8.72)", script)
        self.assertIn("foxSlot.position.set(2.10, 0.02, 8.45)", script)
        self.assertIn("foxSlot.rotation.y = Math.PI", script)
        self.assertIn("karoqSlot.position.set(-2.10, 0.02, 8.72)", script)
        self.assertIn("karoqSlot.rotation.y = 0", script)
        self.assertIn("const GRID_BOX_POSITION = new THREE.Vector3(AUDI_SIDE_FENCE_X - 0.35, 0, -4.20)", script)
        self.assertIn("group.position.copy(GRID_BOX_POSITION)", script)
        self.assertIn("pv: new THREE.Vector3(3.48, 3.18, -5.55)", script)
        self.assertIn("grid: new THREE.Vector3(GRID_BOX_POSITION.x, 1.18, GRID_BOX_POSITION.z)", script)
        self.assertIn("audi: new THREE.Vector3(5.00, 1.72, 1.00)", script)
        self.assertIn("function createCableCurve", script)
        self.assertIn("new THREE.CurvePath", script)
        self.assertIn("new THREE.LineCurve3", script)
        self.assertIn("const pvRoutes = [", script)
        self.assertIn("const pvUnderPanelY", script)
        self.assertIn("[pergolaX(8.02), pvUnderPanelY(pergolaX(8.02)), pergolaZ(-8.56)]", script)
        self.assertIn("const PERGOLA_CENTER = new THREE.Vector3(5.75, 0, -13.10)", script)
        self.assertIn("function createPergolaFurniture", script)
        self.assertNotIn("pvPanelAnchors[0].anchor.toArray()", script)
        self.assertIn('createFlow("pvTrunk"', script)
        self.assertIn("[3.40, 0.18, -1.33]", script)
        self.assertIn("[3.40, BALCONY_FLOOR_Y + 0.08, -1.33]", script)
        self.assertIn("[3.62, BALCONY_RAIL_CENTER_Y, -1.42]", script)
        self.assertIn("{ z: 3.00, length: 6.65, depth: 1.34", script)
        self.assertIn("const SOLARBANK_POSITION = new THREE.Vector3(3.50, BALCONY_FLOOR_Y + 0.06, -1.42)", script)
        self.assertIn("bank.position.copy(SOLARBANK_POSITION)", script)
        self.assertIn("bank.scale.setScalar(2)", script)
        self.assertIn("function createSecondarySolarBank", script)
        self.assertIn("SECONDARY_SOLARBANK_POSITION", script)
        self.assertIn("function createBalconySolarPanels", script)
        self.assertIn('label: "SOLARBANK 3"', script)
        self.assertIn('solix.secondary_solarbank', script)
        self.assertIn('createFlow("secondaryPvTrunk"', script)
        self.assertIn("function createAudiBatteryPack", script)
        self.assertIn("flach im Unterboden zwischen Vorder- und Hinterachse", script)
        self.assertIn("createVerticalBatteryGauge", script)
        self.assertIn("batteryGauges.push(createVerticalBatteryGauge(bank", script)
        self.assertIn("mainY - mainHeight * 0.09", script)
        self.assertIn("gauge.levelFraction = fraction", script)
        self.assertIn("setSchematicBatteryState", script)
        self.assertIn("animateSchematicBattery", script)
        self.assertIn("const levelColor = 0x22c55e", script)
        self.assertIn("const waveColor = discharging ? 0xfb7185 : 0x86efac", script)
        self.assertIn("let cutawayVisible = false", script)
        self.assertIn("const INTERIOR_VIEW_ENABLED = false", script)
        self.assertIn("const CUTAWAY_ENTER_ZOOM = 2.34", script)
        self.assertIn("prepareExteriorFade(exteriorHouse)", script)
        self.assertIn('stage.classList.toggle("house-cutaway", visible)', script)
        self.assertIn('stage.dataset.detailLevel = detailLevel', script)
        self.assertIn('"2 × BP2700"', script)
        self.assertIn("const bankWidth = 0.460 * metre", script)
        self.assertIn("const bpHeight = 0.233 * metre", script)
        self.assertIn("const PV_MODULE_LENGTH = 1.906", script)
        self.assertIn("const PV_MODULE_WIDTH = 1.134", script)
        self.assertIn("const PV_MODULE_VMP = 36.79", script)
        self.assertIn("function createPergolaPanels", script)
        self.assertIn("PERGOLA_PANEL_LAYOUT", script)
        self.assertIn('label: "PERGOLA-PV"', script)
        self.assertIn("panel-mid-detail", script)
        self.assertNotIn("pvSessionWh", script)
        self.assertIn("Anteil aktuell", script)
        self.assertNotIn('"--string-label-angle"', script)
        self.assertNotIn("rotate(var(--string-label-angle", stylesheet)
        self.assertIn("translate(-50%,calc(-100% - 10px))", stylesheet)
        self.assertIn("battery: new THREE.Vector3(3.50, 3.66, -1.42)", script)
        self.assertIn("grid: new THREE.Vector3(GRID_BOX_POSITION.x, 1.18", script)
        self.assertIn("audi: new THREE.Vector3(5.00, 1.72, 1.00)", script)
        self.assertNotIn("Math.atan2(tangentY - y", script)
        self.assertIn('element.classList.toggle("outside"', script)
        self.assertIn(".house-stage.is-building .house-scene-label", stylesheet)
        self.assertIn(".house-stage.is-building .house-menu-toggle", stylesheet)
        self.assertIn(".house-stage.is-building .house-builder-touch-nav", stylesheet)
        self.assertIn("const edgeMarginX = expanded ?", script)
        self.assertIn('className = "house-object-battery unknown"', script)
        self.assertIn("house-scene-head", script)
        self.assertIn("house-scene-detail", script)
        self.assertIn('batteryCharge >= 5 ? "LÄDT · "', script)
        self.assertIn('plugConnected ? "STECKER DRAN"', script)
        self.assertIn("Die animierten 3D-Akkus im Modell bleiben sichtbar", stylesheet)
        self.assertIn('data-flow="charging"', stylesheet)
        self.assertIn('data-flow="discharging"', stylesheet)
        self.assertIn("house-object-battery-wave", stylesheet)
        self.assertIn('setObjectBattery("battery"', script)
        self.assertIn('setObjectBattery("audi"', script)
        self.assertIn("function createAudiChargeConnection", script)
        self.assertIn('createFlow("audiTrunk"', script)
        self.assertNotIn('createFlow("audiLoose"', script)
        self.assertIn("[3.50, BALCONY_RAIL_TOP_Y + 0.10, -1.42]", script)
        self.assertIn("[3.50, BALCONY_FLOOR_Y - 0.10, -0.34]", script)
        self.assertIn("[3.50, 0.16, -1.33]", script)
        self.assertIn("[3.50, 0.16, -1.18],", script)
        self.assertIn("[6.52, 0.16, -1.18], [6.52, 0.16, 0.84]", script)
        self.assertNotIn("[6.52, 0.16, 0.84], [6.52, 0.16, 0.30]", script)
        self.assertNotIn("[6.20, 0.16, -1.55]", script)
        self.assertNotIn('class="house-object-battery-shell"', script)
        self.assertIn("chargingConnection.attached.visible", script)
        self.assertIn("chargingConnection.loose.visible", script)
        self.assertIn("function createInteriorDollhouse", script)
        self.assertIn("function updateCutawayMode", script)
        self.assertIn("function updateInteriorElectricity", script)
        self.assertIn('"Kühlschrank"', script)
        self.assertIn('"Arbeitsplatz · PC"', script)
        self.assertIn('"Waschmaschine"', script)
        self.assertIn("Zwei-Personen-Profil", script)
        self.assertIn("house-cutaway-badge", stylesheet)
        self.assertIn("house-device-label", stylesheet)
        self.assertIn("[GRID_BOX_POSITION.x, 0.58, -4.20]", script)
        self.assertIn("[3.62, 4.84, -3.38]", script)
        self.assertIn("[3.62, 4.84, -2.15]", script)
        self.assertIn("[3.62, BALCONY_RAIL_CENTER_Y, -1.10]", script)
        self.assertIn("[3.50, BALCONY_RAIL_TOP_Y + 0.10, -0.34]", script)
        self.assertIn("RoomEnvironment", script)
        self.assertIn("THREE.PCFShadowMap", script)
        self.assertIn("Feine Ziegelreihen, Traufen und Fallrohre", script)
        self.assertIn("const skylightFrame", script)
        self.assertIn("function createRoofTiles", script)
        self.assertIn("new THREE.InstancedMesh(tileGeometry", script)
        self.assertIn("function makeSkyTexture", script)
        self.assertIn("function createGrassDetail", script)
        self.assertIn("windowReflection", script)
        self.assertIn("[-1.56, 3.18, 0.58, 0.76, slope, PHOTO_CROPS.roof[0]]", script)
        self.assertIn("[1.58, 4.72, 0.68, 0.86, -slope, PHOTO_CROPS.roof[2]]", script)
        self.assertIn('createWindow(house, [3.275, 1.48, 0.42]', script)
        self.assertIn('createWindow(house, [3.275, 1.48, -0.55]', script)
        self.assertIn("[0.88, 0.92]", script)
        self.assertIn("[set.railX, BALCONY_RAIL_TOP_Y, set.z]", script)
        self.assertIn("railX: 4.43", script)
        self.assertIn("{ z: 3.00, length: 6.65", script)
        self.assertNotIn("[3.96, 2.36, panelZ]", script)
        self.assertNotIn('createCar(0x008dc8, "audi-q3")', script)
        self.assertNotIn('createCar(0x1b2329, "skoda-yeti")', script)
        self.assertNotIn('createCar(0x202327, "vw-fox")', script)
        self.assertIn('wheels: []', script)
        self.assertIn('Unsichtbares Pferde-Lade-Rig', script)
        self.assertIn('Unsichtbares Kamel-Lade-Rig', script)
        self.assertNotIn('fallback.visible = true', script)
        self.assertNotIn("function createCarBodyShell", script)
        self.assertNotIn("function createDetailedWheel", script)
        self.assertNotIn("function createCar(", script)
        self.assertNotIn("function createAudiWheelSpinners", script)
        self.assertIn("GLTFLoader", script)
        self.assertIn("MeshoptDecoder", script)
        self.assertIn("/static/models/audi-q3.glb", script)
        self.assertIn("/static/models/skoda-yeti.glb", script)
        self.assertIn("/static/models/vw-fox.glb", script)
        self.assertIn("/static/models/skoda-karoq.glb", script)
        self.assertIn("function loadDetailedVehicles", script)
        self.assertIn("orientation: { x: -Math.PI }", script)
        self.assertIn("length: 3.95", script)
        self.assertIn("length: 3.38", script)
        self.assertIn("length: 3.87", script)
        self.assertIn("vehicle-credits", dashboard)
        self.assertIn('stage.classList.add("is-interacting")', script)
        self.assertIn('state.pointerMode === "pan"', script)
        self.assertIn("function pointerCenter", script)
        self.assertIn("function applyFocalZoom", script)
        self.assertIn("const MIN_ZOOM = 0.55", script)
        self.assertIn("const MAX_ZOOM = 3.10", script)
        self.assertIn("const MIN_PITCH = -0.28", script)
        self.assertIn("state.pinchFocusX", script)
        self.assertIn("state.pinchLastCenterX", script)
        self.assertIn('addEventListener("contextmenu"', script)
        self.assertIn("state.targetPitch", script)
        self.assertIn("state.targetPanX", script)
        self.assertIn("yaw: 0", script)
        self.assertIn("panX: 0.43", script)
        self.assertIn("panY: 1.02", script)
        self.assertIn("zoom: 0.85", script)
        self.assertIn("state.targetYaw = DEFAULT_VIEW.yaw", script)
        self.assertIn("Math.max(0, state.zoom - 1) * 0.20", script)
        self.assertIn("0.64 + state.zoom * 0.32", script)
        self.assertIn("↺ Standardansicht", dashboard)
        self.assertIn("height:100svh", stylesheet)
        self.assertIn("height:100dvh", stylesheet)
        self.assertIn("overscroll-behavior:none", stylesheet)
        self.assertIn(".container > :not(.virtual-house-card)", stylesheet)
        self.assertIn("[3.76, 3.70, -6.57]", script)
        self.assertIn("[-1.92, 0, 1.40]", script)
        self.assertIn("const HOUSE_LENGTH = 12.8", script)
        self.assertIn("function createBayWindow", script)
        self.assertNotIn("const shed = new THREE.Group()", script)
        self.assertIn("touch-action:none", stylesheet)
        self.assertIn(".house-string-label", stylesheet)
        self.assertIn("background:rgba(7,15,27,.50)", stylesheet)
        self.assertIn(".energy-diagram", stylesheet)
        self.assertIn("min-width:0", stylesheet)
        self.assertIn(".container:not(.technical-open) .technical-panel", stylesheet)
        self.assertIn('id="houseMenuToggle"', dashboard)
        self.assertIn('id="menuStartThreshold"', dashboard)
        self.assertIn('id="menuStopThreshold"', dashboard)
        self.assertIn("house-scene-more", script)
        self.assertIn("pvSparklineHtml", script)
        self.assertIn("secondaryBatteryUsageChartHtml", script)
        self.assertIn('class="house-detail-chart"', script)
        self.assertIn("function rolling24HourCaptionHtml", script)
        self.assertIn("function missingChartHistoryHtml", script)
        self.assertIn("(point.time - fixedStart) / windowMs * 100", script)
        self.assertIn("-24 h</span><span>-18 h</span><span>-12 h</span><span>-6 h", script)
        self.assertIn("function chartExtremeMarkers", script)
        self.assertIn("chart-extreme-value", script)
        self.assertIn("Akkukapazität · 24 h", script)
        self.assertNotIn("temperatureChartHtml(secondaryTemperatureHistory", script)
        self.assertIn('"Heute erzeugt"', script)
        self.assertIn('"Aktueller Eingang"', script)
        self.assertIn('"Aktueller Verbrauch"', script)
        self.assertIn("secondary.battery_history", script)
        self.assertIn("state.expandedPanel", script)
        self.assertIn("pv_today_wh_by_string", script)
        self.assertIn("function createHorse", script)
        self.assertIn("function animateHorse", script)
        self.assertIn("function horsePathIsClear", script)
        self.assertIn("function createHorseStableDoor", script)
        self.assertIn('createHorseStableDoor(house, [-3.34, 1.36, -1.58])', script)
        self.assertIn("houseShellGeometry.groups.filter", script)
        self.assertIn("houseShellMaterials", script)
        self.assertIn("stableOpeningWidth = 1.62", script)
        self.assertIn("function horseStableSurfaceHeight", script)
        self.assertIn("ramp.rotation.x = -0.14", script)
        self.assertIn("/static/models/horse-animated.glb?v=80", script)
        self.assertIn('horse.mode === "running" ? "Run" : "Walk"', script)
        self.assertIn('setHorseAnimation(horse, "Eating")', script)
        self.assertIn('setHorseAnimation(horse, "Sleep")', script)
        self.assertIn('setHorseAnimation(horse, "lay_to_idle"', script)
        self.assertIn('setHorseAnimation(horse, "Rear"', script)
        self.assertIn('playAnimalSound("horse"', script)
        self.assertIn("18 + random() * 32", script)
        self.assertIn("150 + horse.random() * 120", script)
        self.assertIn("material.color.setHex(0xe8a866)", script)
        self.assertIn('model.getObjectByName("front_leg_ankle_l")', script)
        self.assertIn("function animateExteriorRoomLights", script)
        self.assertIn("function createStreetLamp", script)
        self.assertIn("lamp.position.set(AUDI_SIDE_FENCE_X - 0.34, 0, 8.72)", script)
        self.assertIn('horseState.navigation = "stable-entry"', script)
        self.assertIn('horse.navigation === "stable-inside"', script)
        self.assertIn('horse.mode = "stable-rest"', script)
        self.assertIn("atParkedCars", script)
        self.assertIn("if (audiModel)", script)
        self.assertIn("function cleanHorseDroppings", script)
        self.assertIn("function restoreAnimalDroppings", script)
        self.assertIn("animalResources.droppings = []", script)
        self.assertIn("async function syncAnimalState", script)
        self.assertIn('fetch("/api/animals"', script)
        self.assertIn('data-animal-action="clean"', script)
        self.assertIn("animalResourceLabelElements", script)
        self.assertIn('className = "animal-resource-label healthy"', script)
        self.assertIn("waterUrgency", script)
        self.assertIn("hayUrgency", script)
        self.assertNotIn('id="houseCleanHorse"', dashboard)
        self.assertIn('id="houseWeather"', dashboard)
        self.assertIn("function animateWeather", script)
        self.assertIn("weather.weather_code", script)
        self.assertIn("PANEL_AZIMUTH_FALLBACK_DEGREES = 157.5", script)
        self.assertIn("function geographicSkyVector", script)
        self.assertIn("azimuthDegrees - configuredPanelAzimuth", script)
        self.assertIn("function updateMoonPhaseTexture", script)
        self.assertIn("moonLight.castShadow = renderProfile.moonShadows", script)
        self.assertIn("weatherVisual.clouds", script)
        self.assertIn("const screenBlue", script)
        self.assertIn("const claddingColors", script)
        self.assertNotIn("zoombarer Innenansicht", dashboard)
        self.assertIn('.house-scene-label[data-component="pv"]', stylesheet)
        self.assertIn("chargingConnection.attachedCable.visible", script)
        self.assertNotIn("FDS-LD-900", script)
        self.assertNotIn("FDS-SR-700", script)
        self.assertNotIn("FDS-SL-600", script)
        self.assertNotIn("FDS-RS-700", script)
        self.assertNotIn("FDS-LS-600", script)
        self.assertIn("pvMinutesIntoDay", script)
        self.assertIn("point.minute / 1440 * 100", script)
        self.assertIn("PV-Tagesverlauf von 00 bis 24 Uhr", script)
        self.assertIn("door-gable-atlas-v4.jpg", script)
        self.assertIn("facade-wall.jpg", script)
        self.assertIn("roof-tiles.jpg", script)
        self.assertIn("front-reference.jpg", script)
        self.assertIn("garden-reference.jpg", script)
        self.assertIn("garage-gable-reference.jpg", script)
        self.assertIn("side-gable-reference.jpg", script)
        self.assertIn("makePhotoCropTexture", script)
        self.assertIn("PHOTO_CROPS.roof", script)
        for filename in (
            "facade-wall.jpg",
            "roof-tiles.jpg",
            "front-reference.jpg",
            "garden-reference.jpg",
            "garage-gable-reference.jpg",
            "side-gable-reference.jpg",
            "door-gable-atlas-v4.jpg",
        ):
            asset = ROOT / "static" / "textures" / "house" / filename
            self.assertTrue(asset.exists())
            self.assertLess(asset.stat().st_size, 1_500_000)
        horse_asset = ROOT / "static" / "models" / "horse-animated.glb"
        self.assertTrue(horse_asset.exists())
        self.assertLess(horse_asset.stat().st_size, 2_000_000)
        camel_asset = ROOT / "static" / "models" / "bactrian-camel.glb"
        self.assertTrue(camel_asset.exists())
        self.assertLess(camel_asset.stat().st_size, 4_500_000)
        self.assertNotIn("FDS-KS-800", script)
        self.assertNotIn("function addVehiclePlates", script)
        self.assertIn("function findHorsePath", script)
        self.assertIn("function createBactrianCamel", script)
        self.assertIn("function loadDetailedCamels", script)
        self.assertIn("/static/models/bactrian-camel.glb?v=82", script)
        self.assertIn("const CAMEL_PASTURE_BOUNDARY", script)
        self.assertIn("pointInPolygon(x, z, CAMEL_PASTURE_BOUNDARY)", script)
        self.assertIn("function distanceToPastureBoundary", script)
        self.assertIn("function camelPathIsClear", script)
        self.assertIn("function rescueStuckCamel", script)
        self.assertIn("camel.stuckFor > 2.4", script)
        self.assertIn("[7.02, -19.20]", script)
        self.assertIn("function createCamelTailRig", script)
        self.assertIn("function animateCamelTail", script)
        self.assertIn("function poseDetailedCamelHead", script)
        self.assertIn("function createAnimalEliminationEffect", script)
        self.assertIn("function updateAnimalEliminationEffect", script)
        self.assertIn("createCamelFeedingRig", script)
        self.assertIn("seconds * (moving ? 5.8 : 3.4)", script)
        self.assertIn("20 + camel.random() * 16", script)
        self.assertIn("facingPoint", script)
        self.assertIn('"Tail0_M_56"', script)
        self.assertIn("function createAnimalCareStations", script)
        self.assertIn("const CAMEL_CARE_STATIONS", script)
        self.assertIn('id: "pergola-camel-hay"', script)
        self.assertIn('id: "pergola-camel-water"', script)
        self.assertIn("createAnimalTrough(station.model, station.resourceKey", script)
        self.assertIn("createHayRack(station.model, station.resourceKey", script)
        self.assertIn("function camelCareTarget", script)
        self.assertIn("CAMEL_CARE_SLOT_SPACING = 2.40", script)
        self.assertIn("CAMEL_HERD_SIZE = 5", script)
        self.assertIn("index < CAMEL_HERD_SIZE", script)
        self.assertIn("const stationIndex = (camel.index ?? 0) % stations.length", script)
        self.assertIn('resourceKey: "waterCamelPool"', script)
        self.assertIn('resourceKey: "hayCamelPergola"', script)
        self.assertIn("camel.hayAppetite", script)
        self.assertIn("camel.waterAppetite", script)
        self.assertNotIn('createAnimalTrough([-10.72, 0, -3.92], "waterHorse")', script)
        self.assertIn('createTroughWater(trough, "waterHorse"', script)
        self.assertIn('horseState.navigation = "stable-water-entry"', script)
        self.assertIn('horse.navigation === "stable-water-inside"', script)
        self.assertIn("function updateAudiWheelRotation", script)
        self.assertNotIn("function collectAudiOriginalWheels", script)
        self.assertNotIn("animateWheels: true", script)
        self.assertIn("source.rotation.y = 0", script)
        self.assertIn("function createCamelWalkRig", script)
        self.assertIn("function animateDetailedCamelGait", script)
        self.assertIn("function animateCamelRestPose", script)
        self.assertIn("function chooseCamelRestTarget", script)
        self.assertIn('camel.mode === "couching"', script)
        self.assertIn("seconds >= camel.nextRestAt && restingCamels < 4", script)
        self.assertIn("-camel.restGroundDrop * bodyDrop", script)
        self.assertIn("limb.front ? -2.28 : 2.42", script)
        self.assertIn("function scheduleCamelHerdRest", script)
        self.assertIn('camel.intent === "herd-rest"', script)
        self.assertIn("animalCareStationBlocksAnimal", script)
        self.assertIn('poseDetailedCamelHead(camel, "idle"', script)
        self.assertIn('playAnimalSound("camel"', script)
        self.assertIn("mirrorSign: -1", script)
        self.assertIn("const jointSign = limb.mirrorSign", script)
        self.assertIn('upper: "Shoulder_L_31"', script)
        self.assertIn('upper: "Hip_R_8"', script)
        self.assertIn("function updateUrinePatches", script)
        self.assertIn("clearcoatRoughness: 0.04", script)
        self.assertIn("const heightScale = 0.18 + level * 0.34", script)
        self.assertIn("random() < 0.94", script)
        self.assertIn('id="animalSoundToggle"', dashboard)
        self.assertIn('addEventListener("touchend", unlockAnimalSounds', script)
        self.assertIn('addEventListener("click", unlockAnimalSounds', script)
        self.assertIn('rel="apple-touch-icon"', dashboard)
        self.assertIn('rel="manifest"', dashboard)
        for filename in ("horse-neigh.ogg", "camel-call.ogg"):
            asset = ROOT / "static" / "sounds" / filename
            self.assertTrue(asset.exists())
            self.assertLess(asset.stat().st_size, 100_000)
        for filename, maximum_size in (
            ("rottweiler-barking.ogg", 400_000),
            ("bird-singing-clear.ogg", 850_000),
        ):
            asset = ROOT / "static" / "sounds" / filename
            self.assertTrue(asset.exists())
            self.assertLess(asset.stat().st_size, maximum_size)
        self.assertNotIn('id="houseFeedAnimals"', dashboard)
        self.assertNotIn('id="houseWaterAnimals"', dashboard)
        self.assertIn('data-animal-action="refill_resource"', script)
        self.assertIn('element.classList.toggle("healthy", value > 50 && !hungryDog)', script)
        self.assertIn('element.classList.toggle("refill", value <= 50 && value > 20 && !hungryDog)', script)
        self.assertIn('element.classList.toggle("warning", (value <= 20 && value > 10) || hungryDog)', script)
        self.assertIn('element.classList.toggle("critical", value <= 10)', script)
        self.assertIn(".animal-resource-label.healthy", stylesheet)
        self.assertIn(".animal-resource-label.refill", stylesheet)
        self.assertIn(".animal-resource-label.warning", stylesheet)
        self.assertIn(".animal-resource-label.critical", stylesheet)
        self.assertIn("function createGardenBirds", script)
        self.assertIn("function animateGardenBirds", script)
        self.assertIn("function playBirdSong", script)
        self.assertIn('activity: "drinking-pool"', script)
        self.assertIn('activity: "drinking-trough"', script)
        for species in (
            "Haussperling", "Feldsperling", "Rotkehlchen", "Kohlmeise",
            "Blaumeise", "Buchfink", "Grünfink", "Stieglitz", "Star",
            "Amsel", "Singdrossel", "Bachstelze", "Hausrotschwanz",
            "Zaunkönig", "Elster", "Rabenkrähe", "Eichelhäher",
            "Buntspecht", "Ringeltaube", "Türkentaube", "Teichhuhn",
            "Purpurhuhn",
        ):
            self.assertIn(f'name: "{species}"', script)
        self.assertIn('name: "Purpurhuhn"', script)
        self.assertIn("function createBirdActions", script)
        self.assertIn('sparrow: "/static/models/bird-sparrow-quirky.glb?v=106"', script)
        self.assertIn('eat: birdClipByWords(animations', script)
        self.assertIn('bird.activity === "feeding" ? "eat" : "idle"', script)
        self.assertIn('setBirdAnimation(bird, "landing"', script)
        self.assertIn('setBirdAnimation(bird, "walking"', script)
        self.assertIn('setBirdAnimation(bird, flightAction', script)
        self.assertIn("const MAX_ACTIVE_BIRD_VISITORS = 20", script)
        self.assertIn('name: "Ringeltaube", model: "pigeon", length: 0.36', script)
        self.assertIn('name: "Türkentaube", model: "pigeon", length: 0.28', script)
        self.assertIn("nextVisitAt: 2 + index * 1.8 + random() * 4", script)
        self.assertIn("bird.singingUntil = seconds + duration", script)
        self.assertIn('let flying = bird.state.startsWith("flying")', script)
        self.assertIn("flying = true", script)
        self.assertIn("seconds + 4 + bird.random() * 5", script)
        self.assertIn("stage.dataset.birdSpeciesCount", script)
        self.assertIn("stage.dataset.birdVisitorLimit", script)
        self.assertIn("stage.dataset.birdSinging", script)
        self.assertIn("stage.dataset.birdMissingAnimations", script)
        self.assertIn("const modelLength = Math.max(size.x * morph[0], size.z * morph[1]", script)
        self.assertIn("const baseScale = config.length / modelLength", script)
        self.assertIn("model.rotation.y = Math.PI", script)
        self.assertIn("stage.dataset.birdScaleAudit", script)
        self.assertIn("stage.dataset.birdFlightAlignment", script)
        self.assertIn("stage.dataset.birdSongCount", script)
        self.assertIn("volume: 0.027", script)
        self.assertIn("function createRottweiler", script)
        self.assertIn("function animateDog", script)
        self.assertIn("function playDogBark", script)
        self.assertIn("function loadDetailedRottweiler", script)
        self.assertIn('rottweiler-meshy/rottweiler-realistic-animated.glb?v=121', script)
        self.assertIn('"meshy-m2m-rigged"', script)
        self.assertIn('tuneRottweilerMaterials(model, assetKind === "meshy-m2m-rigged")', script)
        self.assertIn("const targetHeight = 0.78", script)
        self.assertIn("nextFoodVisitAt", script)
        self.assertIn("const setCareBone", script)
        self.assertNotIn("neck.rotation.x += 0.52", script)
        self.assertIn('rottweiler-benny/rottweiler-animated.glb?v=112', script)
        self.assertIn('rottweiler/scene.gltf?v=108', script)
        self.assertIn('new Audio("/static/sounds/rottweiler-barking.ogg?v=108")', script)
        self.assertIn('new Audio("/static/sounds/bird-singing-clear.ogg?v=108")', script)
        self.assertIn("new THREE.AnimationMixer(model)", script)
        self.assertIn("function createDogActions", script)
        self.assertIn('setDogAnimation(dogState, sleeping ? "sleep"', script)
        self.assertIn("stage.dataset.dogAsset", script)
        self.assertIn("stage.dataset.dogAnimation", script)
        self.assertIn('group.name = "Animierter Rottweiler"', script)
        self.assertIn('"dog-food"', script)
        self.assertIn('"dog-water"', script)
        self.assertIn("animalResources.dogHungry", script)
        self.assertIn("startBirdDeparture(bird, seconds)", script)
        self.assertIn('animalMotionPose("dog"', script)
        self.assertIn("function syncAnimalMotion", script)
        self.assertIn("reconcileSharedAnimalMotion(delta)", script)
        self.assertIn("stage.dataset.animalMotionRole", script)
        for filename in (
            "bird-pigeon-animated.glb", "bird-sparrow-quirky.glb", "bird-swamphen.glb"
        ):
            bird_asset = ROOT / "static" / "models" / filename
            self.assertTrue(bird_asset.exists())
            self.assertLess(bird_asset.stat().st_size, 3_000_000)
        rottweiler_model = ROOT / "static" / "models" / "rottweiler" / "scene.gltf"
        rottweiler_binary = ROOT / "static" / "models" / "rottweiler" / "scene.bin"
        self.assertTrue(rottweiler_model.exists())
        self.assertTrue(rottweiler_binary.exists())
        self.assertLess(rottweiler_model.stat().st_size + rottweiler_binary.stat().st_size, 250_000)
        animated_rottweiler = (ROOT / "static" / "models" /
                               "rottweiler-benny" / "rottweiler-animated.glb")
        self.assertTrue(animated_rottweiler.exists())
        self.assertLess(animated_rottweiler.stat().st_size, 400_000)
        realistic_rottweiler = (ROOT / "static" / "models" /
                                "rottweiler-meshy" /
                                "rottweiler-realistic-animated.glb")
        self.assertTrue(realistic_rottweiler.exists())
        self.assertLess(realistic_rottweiler.stat().st_size, 1_000_000)
        self.assertTrue((ROOT / "static" / "models" /
                         "rottweiler-meshy" / "LICENSE.txt").exists())
        self.assertIn("Benny, the Rottweiler", (ROOT / "THIRD_PARTY_NOTICES.md").read_text())
        self.assertIn("Benny, the Rottweiler", (ROOT / "templates" / "index.html").read_text())
        self.assertNotIn('bird-swamphen-nestling.glb?v=', script)
        self.assertIn("function createTroughWater", script)
        self.assertIn("function animateTroughWater", script)
        self.assertIn('ior: 1.333', script)
        self.assertIn("function updateSeasonalScene", script)
        self.assertIn('spring: "Frühling"', script)
        self.assertIn('summer: "Sommer"', script)
        self.assertIn('autumn: "Herbst"', script)
        self.assertIn('winter: "Winter"', script)

    def test_mobile_render_profile_and_house_builder_are_available(self) -> None:
        dashboard = (ROOT / "templates" / "index.html").read_text(encoding="utf-8")
        script = (ROOT / "static" / "house.js").read_text(encoding="utf-8")
        stylesheet = (ROOT / "static" / "style.css").read_text(encoding="utf-8")

        for element_id in (
            "renderQualitySelect", "houseBuilderOpen", "houseBuilderPanel",
            "builderPartType", "builderVariant", "builderColor",
            "builderVariantLabel", "builderWallLengthRow", "builderWallLength",
            "builderWallLengthValue",
            "builderPanelToggle", "builderRotateLeft", "builderRotateRight",
            "builderNew", "builderDelete", "builderUndo", "builderClear",
            "builderSelectionTools", "builderSelectionRotateLeft",
            "builderSelectionRotateRight", "builderSelectionDelete",
            "sceneLoader", "sceneLoaderBar", "sceneLoaderStatus", "sceneLoaderPercent",
            "sceneLoaderVersion",
        ):
            self.assertIn(f'id="{element_id}"', dashboard)

        self.assertIn('const APP_BUILD_VERSION = "129"', script)
        self.assertIn("Version 129", dashboard)

        self.assertIn('targetFps: 30, pixelRatio: 1.15', script)
        self.assertIn('targetFps: 24, pixelRatio: 1', script)
        self.assertIn('stage.dataset.targetFps = String(renderProfile.targetFps)', script)
        self.assertIn('renderer.shadowMap.autoUpdate = renderProfile.shadowInterval === 1', script)
        self.assertIn('const activeBirdVisitorLimit = Math.min', script)
        self.assertIn('if (lastRenderedAt && time - lastRenderedAt < frameInterval - 1)', script)
        self.assertIn('renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, renderProfile.pixelRatio))', script)
        self.assertIn('const BUILDER_VARIANTS = Object.freeze', script)
        self.assertIn('const BUILDER_ROTATION_STEP = 90', script)
        self.assertIn('Math.round(value / BUILDER_ROTATION_STEP)', script)
        self.assertIn('function orthogonalWallPoint(start, point)', script)
        self.assertIn('rotateSelection(-BUILDER_ROTATION_STEP)', script)
        self.assertIn('rotateSelection(BUILDER_ROTATION_STEP)', script)
        self.assertNotIn('rotateSelection(-15)', script)
        self.assertNotIn('rotateSelection(15)', script)
        self.assertIn('const sceneLoadingManager = new THREE.LoadingManager()', script)
        self.assertIn('new THREE.TextureLoader(sceneLoadingManager)', script)
        self.assertIn('new GLTFLoader(sceneLoadingManager)', script)
        self.assertIn('function resumeSceneWithLoader()', script)
        self.assertIn('document.addEventListener("visibilitychange"', script)
        self.assertIn('window.addEventListener("pagehide"', script)
        self.assertIn('sceneLoadingManager.itemStart(SCENE_BOOTSTRAP_ITEM)', script)
        self.assertIn('sceneLoadingManager.itemEnd(SCENE_BOOTSTRAP_ITEM)', script)
        self.assertIn('function createHouseBuilder()', script)
        self.assertIn('function createBuilderPart(item)', script)
        self.assertIn('new THREE.GridHelper(20, 20', script)
        self.assertIn('function snapOpeningToWall(item, rawX, rawZ, onlyWallId = null)', script)
        self.assertIn('function updateWallPreview(point)', script)
        self.assertIn('function finishWallDrawing(cancelled = false)', script)
        self.assertIn('fenceDrawPreview.name = "Zaun-Zeichenvorschau"', script)
        self.assertIn('function showFenceDrawPreview(length, center, rotation)', script)
        self.assertIn('["wall", "fence"].includes(drawType)', script)
        self.assertIn('builder.drawType = drawType', script)
        self.assertIn('function positionOpeningOnWall(item)', script)
        self.assertIn('function updateAttachedOpenings(wallId)', script)
        self.assertIn('id: "wall-custom-standard"', script)
        self.assertIn('id: "floor-stone"', script)
        self.assertIn('id: "grass-lawn"', script)
        self.assertIn('id: "fence-picket"', script)
        self.assertIn('id: "tree-deciduous"', script)
        self.assertIn('id: "tree-birch"', script)
        self.assertIn('<option value="fence">', dashboard)
        self.assertIn('function builderItemHitAtPointer(event)', script)
        self.assertIn('function snapWallPoint(point, excludeWallId = null)', script)
        self.assertIn('const WALL_ENDPOINT_SNAP_DISTANCE = 0.95', script)
        self.assertIn('activatePointerMode();', script)
        self.assertIn('function createPlacementPreview()', script)
        self.assertIn('function updatePlacementPreview(event)', script)
        self.assertIn('function previewPlacementAtPointer(event)', script)
        self.assertIn('builder.placementEnabled', script)
        self.assertIn('id="builderPointerMode"', dashboard)
        self.assertIn('stage.dataset.builderPlacementPreview = valid ? "valid" : "invalid"', script)
        self.assertIn('houseBuilder.hoverPointer(event)', script)
        self.assertIn('clickedItem?.type === "wall"', script)
        self.assertIn('function beginPointer(event)', script)
        self.assertIn('function movePointer(event)', script)
        self.assertIn('builder.selectionHelper = new THREE.BoxHelper', script)
        self.assertIn('scene.add(builder.selectionHelper)', script)
        self.assertIn('scene.remove(builder.selectionHelper)', script)
        self.assertIn('function updateSelectionToolsPosition()', script)
        self.assertIn('builderSelectionDelete.addEventListener("click", deleteSelection)', script)
        self.assertIn('window.solixHouseBuilder', script)
        self.assertIn('.house-builder-panel', stylesheet)
        self.assertIn('.house-builder-selection-tools', stylesheet)
        self.assertIn('.house-builder-panel.is-collapsed', stylesheet)
        self.assertIn('.house-stage.is-building', stylesheet)
        self.assertIn('bottom:max(12px,env(safe-area-inset-bottom))', stylesheet)
        self.assertIn('scrollbar-gutter:stable', stylesheet)
        self.assertIn('.scene-loader{', stylesheet)
        self.assertIn('id="automationHistory"', dashboard)
        self.assertIn("function createAudiBrakeLights", script)
        self.assertIn("function startAudiPresenceTransition", script)
        self.assertIn("function updateAudiPresenceMotion", script)
        self.assertIn("function runAudiPresenceDemo", script)
        self.assertIn("const AUDI_DEPARTURE_ROUTE", script)
        self.assertIn("const AUDI_ARRIVAL_ROUTE", script)
        self.assertIn("{ x: 0.00, z: 14.15, yaw: Math.PI / 2 }", script)
        self.assertIn("{ x: 4.80, z: 7.00, yaw: Math.PI }", script)
        self.assertIn("const AUDI_OFFSCREEN_POSE = Object.freeze({ x: 11.45", script)
        self.assertIn("function audiRouteTangent", script)
        self.assertIn("const segmentDuration = Math.max", script)
        self.assertIn("const AUDI_ARRIVAL_ENTRY_POSE = Object.freeze({ x: 9.45, z: -18.50", script)
        self.assertIn("function followAudiRoute", script)
        self.assertIn("setAudiConnectionForPresence(\"driving\")", script)
        self.assertIn('get("audi_demo") === "1"', script)
        self.assertIn('motion.phase === "departing"', script)
        self.assertIn('audiPresenceMotion.phase = atHome ? "arriving" : "departing"', script)
        self.assertIn('audiAtHome === false ? "UNTERWEGS"', script)
        self.assertNotIn(".house-stage.is-interacting .house-scene-label", stylesheet)
        self.assertIn("rgba(7,15,27,.58)", stylesheet)
        self.assertIn("rgba(7,15,27,.50)", stylesheet)
        self.assertIn('function markerHiddenByHouse(worldAnchor)', script)
        self.assertIn('classList.toggle("occluded", occluded)', script)
        self.assertIn('.house-click-marker.occluded', stylesheet)
        self.assertIn('.house-stage.is-building .house-click-marker', stylesheet)

    def test_garages_domestic_fleet_and_on_demand_cards_are_available(self) -> None:
        dashboard = (ROOT / "templates" / "index.html").read_text(encoding="utf-8")
        script = (ROOT / "static" / "house.js").read_text(encoding="utf-8")
        stylesheet = (ROOT / "static" / "style.css").read_text(encoding="utf-8")

        self.assertIn("function createGarageDoors", script)
        self.assertIn("function createGarageInterior", script)
        self.assertIn("Garage ${index + 1} · Innenraum", script)
        self.assertIn("GABLE_Z - 3.02", script)
        self.assertIn("const innerThreshold", script)
        self.assertIn("const domesticFleet", script)
        self.assertIn("function domesticAwayRoute", script)
        self.assertIn("function domesticReturnRoute", script)
        self.assertIn("function domesticGarageRoute", script)
        self.assertIn('createDomesticVehicleController("yeti"', script)
        self.assertIn('createDomesticVehicleController("karoq"', script)
        self.assertIn('createDomesticVehicleController("fox"', script)
        self.assertIn('garageDoor: "middle"', script)
        self.assertIn('garageDoor: "left"', script)
        self.assertIn('fetch("/api/garage"', script)
        self.assertIn('fetch("/api/garage/middle"', script)
        self.assertIn("window.confirm(question)", script)
        self.assertIn("house-click-marker", script)
        self.assertNotIn('marker.textContent = "i"', script)
        self.assertIn("expandedAnimalResource", script)
        self.assertIn(".house-scene-label:not(.expanded)", stylesheet)
        self.assertIn('content:"✦"', stylesheet)
        self.assertIn("scene-click-sparkle", stylesheet)
        self.assertIn(".animal-resource-label:not(.expanded)", stylesheet)
        self.assertIn(".house-component-legend[hidden]", stylesheet)
        self.assertIn('class="house-component-legend"', dashboard)
        self.assertIn('aria-label="Komponenten im virtuellen Haus" hidden', dashboard)

    def test_vehicle_assets_are_web_optimized_and_attributed(self) -> None:
        dashboard = (ROOT / "templates" / "index.html").read_text(encoding="utf-8")
        attributions = (ROOT / "static" / "models" / "ATTRIBUTIONS.md").read_text(encoding="utf-8")

        for filename in ("audi-q3.glb", "skoda-yeti.glb", "vw-fox.glb", "skoda-karoq.glb"):
            asset = ROOT / "static" / "models" / filename
            self.assertTrue(asset.exists())
            self.assertLess(asset.stat().st_size, 2_000_000)

        self.assertIn("2023 Audi Q3 40 TFSI", dashboard)
        self.assertIn("Ddiaz Design", dashboard)
        self.assertIn("2019 Skoda Karoq", dashboard)
        self.assertIn("BHP3D", attributions)
        self.assertIn("Bactrian Camel (Low Poly)", attributions)
        self.assertIn("Nyilonelycompany", dashboard)
        self.assertIn("CC BY-NC-SA 4.0", attributions)


if __name__ == "__main__":
    unittest.main()
