from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class DashboardSchematicTests(unittest.TestCase):
    def test_schematic_contains_every_energy_component(self) -> None:
        dashboard = (ROOT / "templates" / "index.html").read_text(encoding="utf-8")

        for component_id in (
            "diagramNodePv",
            "diagramNodeSolix",
            "diagramNodeGrid",
            "diagramNodeHome",
            "diagramNodeOther",
            "diagramNodePlug",
            "diagramNodeAudi",
        ):
            self.assertIn(f'id="{component_id}"', dashboard)

        self.assertIn("Energiefluss im Gesamtsystem", dashboard)
        self.assertIn("style.css?v=20260807-58", dashboard)
        self.assertIn("house.js?v=20260807-58", dashboard)
        self.assertIn("app.js?v=20260805-44", dashboard)
        self.assertIn('type="module" src="/static/house.js', dashboard)
        self.assertIn("three@0.185.1", dashboard)

    def test_schematic_is_wired_to_live_values(self) -> None:
        script = (ROOT / "static" / "app.js").read_text(encoding="utf-8")

        for live_value in (
            "battery_discharge_power",
            "system_output_power",
            "smartPlug.power_w",
            "audi.battery_percent",
            "remaining_charging_minutes",
        ):
            self.assertIn(live_value, script)

        self.assertIn('setDiagramLink("diagramLinkAudi", charging)', script)
        self.assertNotIn('getElementById("flowPV")', script)

    def test_virtual_house_is_touch_enabled_and_uses_live_data(self) -> None:
        dashboard = (ROOT / "templates" / "index.html").read_text(encoding="utf-8")
        script = (ROOT / "static" / "house.js").read_text(encoding="utf-8")
        stylesheet = (ROOT / "static" / "style.css").read_text(encoding="utf-8")

        self.assertIn('id="houseCanvas"', dashboard)
        self.assertIn('id="houseReset"', dashboard)
        self.assertIn('addEventListener("pointermove"', script)
        self.assertIn('addEventListener("wheel"', script)
        self.assertIn("pointerDistance", script)
        self.assertIn('addEventListener("solix-dashboard-data"', script)
        self.assertIn('label: "AUDI Q3"', script)
        self.assertIn("WebGLRenderer", script)
        self.assertIn("MeshPhysicalMaterial", script)
        self.assertIn("shadowMap.enabled", script)
        self.assertNotIn('label: "SMART PLUG"', script)
        self.assertNotIn('label: "HAUSGERÄTE"', script)
        self.assertIn('solix["pv" + number]', script)
        self.assertIn('createFlow(panel.id', script)
        self.assertIn('className = "house-string-label"', script)
        self.assertIn('createDoor(house, [3.285, 3.58, 4.10]', script)
        self.assertIn('createDoor(house, [3.285, 3.58, 1.45]', script)
        self.assertIn('createWindow(house, [3.285, 3.66, 0.18]', script)
        self.assertIn('createDoor(house, [3.285, 3.58, -4.06]', script)
        self.assertIn('createFrontWoodDoor(house, [3.30, 1.35, -3.15]', script)
        self.assertIn('createDoor(house, [3.30, 1.35, -4.30]', script)
        self.assertIn('createDoor(house, [-3.30, 1.34, -3.55]', script)
        self.assertIn('createDoor(house, [-3.285, 3.58, -3.62]', script)
        self.assertIn("function createJulietGuard", script)
        self.assertIn("function createWoodDoorWithCanopy", script)
        self.assertIn("function createFrontWoodDoor", script)
        self.assertIn('createWoodDoorWithCanopy(house, [-3.30, 1.34, 1.80], CLEAN_OPENINGS.door.wood)', script)
        self.assertIn('path: "/static/textures/house/window-atlas-clean-v2.jpg"', script)
        self.assertIn('path: "/static/textures/house/door-atlas-clean-v2.jpg"', script)
        self.assertIn("cleanAsset: true", script)
        self.assertIn("if (!cleanAsset)", script)
        self.assertTrue((ROOT / "static" / "textures" / "house" / "window-atlas-clean-v2.jpg").is_file())
        self.assertTrue((ROOT / "static" / "textures" / "house" / "door-atlas-clean-v2.jpg").is_file())
        self.assertIn("Gartenfassade aus IMG_7397", script)
        self.assertIn("[0.16, 4.90, 2.45]", script)
        self.assertIn("[5.22, 1.02]", script)
        self.assertIn('createWindow(house, [-3.30, 1.48, 5.08]', script)
        self.assertIn('THREE.MathUtils.degToRad(-40)', script)
        self.assertIn("pool.position.set(-7.55, 0, -6.72)", script)
        self.assertIn("Begehbare Holzumrandung", script)
        self.assertIn("[-11.70, 0.39, z]", script)
        self.assertIn("const AUDI_SIDE_FENCE_X = 7.20", script)
        self.assertIn("const rearFenceLength = AUDI_SIDE_FENCE_X + 11.70", script)
        self.assertNotIn("const hedge =", script)
        self.assertIn("createTree(0.35, -8.65, 0.94)", script)
        self.assertNotIn("createTree(1.10, -8.55, 0.72)", script)
        self.assertIn("[10.05, 0.07, 6.1]", script)
        self.assertIn("[3.2, 0.07, 13.2]", script)
        self.assertIn("yetiSlot.position.set(0, 0.02, 8.72)", script)
        self.assertIn("foxSlot.position.set(2.10, 0.02, 8.45)", script)
        self.assertIn("foxSlot.rotation.y = Math.PI", script)
        self.assertIn("karoqSlot.position.set(-2.10, 0.02, 8.72)", script)
        self.assertIn("karoqSlot.rotation.y = 0", script)
        self.assertIn("const GRID_BOX_POSITION = new THREE.Vector3(AUDI_SIDE_FENCE_X - 0.35, 0, -4.20)", script)
        self.assertIn("group.position.copy(GRID_BOX_POSITION)", script)
        self.assertIn("pv: new THREE.Vector3(3.48, 3.18, -5.55)", script)
        self.assertIn("grid: new THREE.Vector3(GRID_BOX_POSITION.x, 1.18, GRID_BOX_POSITION.z)", script)
        self.assertIn("audi: new THREE.Vector3(5.00, 1.72, 1.00)", script)
        self.assertIn("function createCableCurve", script)
        self.assertIn("new THREE.CurvePath", script)
        self.assertIn("new THREE.LineCurve3", script)
        self.assertIn("const pvRoutes = [", script)
        self.assertIn("const pvUnderPanelY", script)
        self.assertIn("[pergolaX(8.02), pvUnderPanelY(pergolaX(8.02)), -8.56]", script)
        self.assertNotIn("pvPanelAnchors[0].anchor.toArray()", script)
        self.assertIn('createFlow("pvTrunk"', script)
        self.assertIn("[3.40, 0.18, -1.33]", script)
        self.assertIn("[3.40, BALCONY_FLOOR_Y + 0.08, -1.33]", script)
        self.assertIn("[3.62, BALCONY_RAIL_CENTER_Y, -1.42]", script)
        self.assertIn("{ z: 3.00, length: 6.65, depth: 1.34", script)
        self.assertIn("const SOLARBANK_POSITION = new THREE.Vector3(3.50, BALCONY_FLOOR_Y + 0.06, -1.42)", script)
        self.assertIn("bank.position.copy(SOLARBANK_POSITION)", script)
        self.assertIn("bank.scale.setScalar(2)", script)
        self.assertIn("function createAudiBatteryPack", script)
        self.assertIn("flach im Unterboden zwischen Vorder- und Hinterachse", script)
        self.assertIn("createVerticalBatteryGauge", script)
        self.assertIn("batteryGauges.push(createVerticalBatteryGauge(bank", script)
        self.assertIn("mainY - mainHeight * 0.09", script)
        self.assertIn("gauge.levelFraction = fraction", script)
        self.assertIn("setSchematicBatteryState", script)
        self.assertIn("animateSchematicBattery", script)
        self.assertIn("const levelColor = 0x22c55e", script)
        self.assertIn("const waveColor = discharging ? 0xfb7185 : 0x86efac", script)
        self.assertIn("let cutawayVisible = false", script)
        self.assertIn("const CUTAWAY_ENTER_ZOOM = 2.34", script)
        self.assertIn("prepareExteriorFade(exteriorHouse)", script)
        self.assertIn('stage.classList.toggle("house-cutaway", visible)', script)
        self.assertIn('stage.dataset.detailLevel = detailLevel', script)
        self.assertIn('"2 × BP2700"', script)
        self.assertIn("const bankWidth = 0.460 * metre", script)
        self.assertIn("const bpHeight = 0.233 * metre", script)
        self.assertIn("const PV_MODULE_LENGTH = 1.906", script)
        self.assertIn("const PV_MODULE_WIDTH = 1.134", script)
        self.assertIn("const PV_MODULE_VMP = 36.79", script)
        self.assertIn("function createPergolaPanels", script)
        self.assertIn("PERGOLA_PANEL_LAYOUT", script)
        self.assertIn('label: "PERGOLA-PV"', script)
        self.assertIn("panel-mid-detail", script)
        self.assertNotIn("pvSessionWh", script)
        self.assertIn("Anteil aktuell", script)
        self.assertNotIn('"--string-label-angle"', script)
        self.assertNotIn("rotate(var(--string-label-angle", stylesheet)
        self.assertIn("translate(-50%,calc(-100% - 10px))", stylesheet)
        self.assertIn("battery: new THREE.Vector3(3.50, 3.66, -1.42)", script)
        self.assertIn("grid: new THREE.Vector3(GRID_BOX_POSITION.x, 1.18", script)
        self.assertIn("audi: new THREE.Vector3(5.00, 1.72, 1.00)", script)
        self.assertNotIn("Math.atan2(tangentY - y", script)
        self.assertIn('element.classList.toggle("outside"', script)
        self.assertIn("const edgeMarginX = expanded ?", script)
        self.assertIn('className = "house-object-battery unknown"', script)
        self.assertIn("house-scene-head", script)
        self.assertIn("house-scene-detail", script)
        self.assertIn('batteryCharge >= 5 ? "LÄDT · "', script)
        self.assertIn('plugConnected ? "STECKER DRAN"', script)
        self.assertIn("Die animierten 3D-Akkus im Modell bleiben sichtbar", stylesheet)
        self.assertIn('data-flow="charging"', stylesheet)
        self.assertIn('data-flow="discharging"', stylesheet)
        self.assertIn("house-object-battery-wave", stylesheet)
        self.assertIn('setObjectBattery("battery"', script)
        self.assertIn('setObjectBattery("audi"', script)
        self.assertIn("function createAudiChargeConnection", script)
        self.assertIn('createFlow("audiTrunk"', script)
        self.assertNotIn('createFlow("audiLoose"', script)
        self.assertIn("[3.50, BALCONY_RAIL_TOP_Y + 0.10, -1.42]", script)
        self.assertIn("[3.50, BALCONY_FLOOR_Y - 0.10, -0.34]", script)
        self.assertIn("[3.50, 0.16, -1.33]", script)
        self.assertIn("[3.50, 0.16, -1.18],", script)
        self.assertIn("[6.52, 0.16, -1.18], [6.52, 0.16, 0.84]", script)
        self.assertNotIn("[6.52, 0.16, 0.84], [6.52, 0.16, 0.30]", script)
        self.assertNotIn("[6.20, 0.16, -1.55]", script)
        self.assertNotIn('class="house-object-battery-shell"', script)
        self.assertIn("chargingConnection.attached.visible", script)
        self.assertIn("chargingConnection.loose.visible", script)
        self.assertIn("function createInteriorDollhouse", script)
        self.assertIn("function updateCutawayMode", script)
        self.assertIn("function updateInteriorElectricity", script)
        self.assertIn('"Kühlschrank"', script)
        self.assertIn('"Arbeitsplatz · PC"', script)
        self.assertIn('"Waschmaschine"', script)
        self.assertIn("Zwei-Personen-Profil", script)
        self.assertIn("house-cutaway-badge", stylesheet)
        self.assertIn("house-device-label", stylesheet)
        self.assertIn("[GRID_BOX_POSITION.x, 0.58, -4.20]", script)
        self.assertIn("[3.62, 4.84, -3.38]", script)
        self.assertIn("[3.62, 4.84, -2.15]", script)
        self.assertIn("[3.62, BALCONY_RAIL_CENTER_Y, -1.10]", script)
        self.assertIn("[3.50, BALCONY_RAIL_TOP_Y + 0.10, -0.34]", script)
        self.assertIn("RoomEnvironment", script)
        self.assertIn("THREE.VSMShadowMap", script)
        self.assertIn("Feine Ziegelreihen, Traufen und Fallrohre", script)
        self.assertIn("const skylightFrame", script)
        self.assertIn("function createRoofTiles", script)
        self.assertIn("new THREE.InstancedMesh(tileGeometry", script)
        self.assertIn("function makeSkyTexture", script)
        self.assertIn("function createGrassDetail", script)
        self.assertIn("windowReflection", script)
        self.assertIn("[-1.62, -2.72, 0.58, 0.76, slope, PHOTO_CROPS.roof[0]]", script)
        self.assertIn("[1.58, 4.48, 0.68, 0.86, -slope, PHOTO_CROPS.roof[2]]", script)
        self.assertIn("[0.42, -0.55].forEach", script)
        self.assertIn("[0.88, 0.92]", script)
        self.assertIn("[set.railX, BALCONY_RAIL_TOP_Y, set.z]", script)
        self.assertIn("railX: 4.43", script)
        self.assertIn("{ z: 3.00, length: 6.65", script)
        self.assertNotIn("[3.96, 2.36, panelZ]", script)
        self.assertIn('createCar(0x008dc8, "audi-q3")', script)
        self.assertIn('createCar(0x1b2329, "skoda-yeti")', script)
        self.assertIn('createCar(0x202327, "vw-fox")', script)
        self.assertIn("function createCarBodyShell", script)
        self.assertIn("function createDetailedWheel", script)
        self.assertIn("GLTFLoader", script)
        self.assertIn("MeshoptDecoder", script)
        self.assertIn("/static/models/audi-q3.glb", script)
        self.assertIn("/static/models/skoda-yeti.glb", script)
        self.assertIn("/static/models/vw-fox.glb", script)
        self.assertIn("/static/models/skoda-karoq.glb", script)
        self.assertIn("function loadDetailedVehicles", script)
        self.assertIn("orientation: { x: -Math.PI }", script)
        self.assertIn("length: 3.95", script)
        self.assertIn("length: 3.38", script)
        self.assertIn("length: 3.87", script)
        self.assertIn("vehicle-credits", dashboard)
        self.assertIn('stage.classList.add("is-interacting")', script)
        self.assertIn('state.pointerMode === "pan"', script)
        self.assertIn("function pointerCenter", script)
        self.assertIn("function applyFocalZoom", script)
        self.assertIn("const MIN_ZOOM = 0.55", script)
        self.assertIn("const MAX_ZOOM = 3.10", script)
        self.assertIn("const MIN_PITCH = -0.28", script)
        self.assertIn("state.pinchFocusX", script)
        self.assertIn("state.pinchLastCenterX", script)
        self.assertIn('addEventListener("contextmenu"', script)
        self.assertIn("state.targetPitch", script)
        self.assertIn("state.targetPanX", script)
        self.assertIn("yaw: -1.567337267354423", script)
        self.assertIn("state.targetYaw = DEFAULT_VIEW.yaw", script)
        self.assertIn("Math.max(0, state.zoom - 1) * 0.20", script)
        self.assertIn("0.64 + state.zoom * 0.32", script)
        self.assertIn("↺ Standardansicht", dashboard)
        self.assertIn("height:100svh", stylesheet)
        self.assertIn("height:100dvh", stylesheet)
        self.assertIn("overscroll-behavior:none", stylesheet)
        self.assertIn(".container > :not(.virtual-house-card)", stylesheet)
        self.assertIn("[3.76, 3.70, -6.57]", script)
        self.assertIn("[-1.92, 0, 1.40]", script)
        self.assertIn("const HOUSE_LENGTH = 12.8", script)
        self.assertIn("function createBayWindow", script)
        self.assertNotIn("const shed = new THREE.Group()", script)
        self.assertIn("touch-action:none", stylesheet)
        self.assertIn(".house-string-label", stylesheet)
        self.assertIn("background:rgba(7,15,27,.78)", stylesheet)
        self.assertIn(".energy-diagram", stylesheet)
        self.assertIn("min-width:0", stylesheet)
        self.assertIn(".container:not(.technical-open) .technical-panel", stylesheet)
        self.assertIn('id="houseMenuToggle"', dashboard)
        self.assertIn('id="menuStartThreshold"', dashboard)
        self.assertIn('id="menuStopThreshold"', dashboard)
        self.assertIn("house-scene-more", script)
        self.assertIn("pvSparklineHtml", script)
        self.assertIn("state.expandedPanel", script)
        self.assertIn("pv_today_wh_by_string", script)
        self.assertIn('.house-scene-label[data-component="pv"]', stylesheet)
        self.assertIn("chargingConnection.attachedCable.visible", script)
        self.assertIn("FDS-LD-900", script)
        self.assertIn("FDS-RS-700", script)
        self.assertIn("FDS-LS-600", script)
        self.assertIn("facade-wall.jpg", script)
        self.assertIn("roof-tiles.jpg", script)
        self.assertIn("front-reference.jpg", script)
        self.assertIn("garden-reference.jpg", script)
        self.assertIn("garage-gable-reference.jpg", script)
        self.assertIn("side-gable-reference.jpg", script)
        self.assertIn("makePhotoCropTexture", script)
        self.assertIn("PHOTO_CROPS.roof", script)
        for filename in (
            "facade-wall.jpg",
            "roof-tiles.jpg",
            "front-reference.jpg",
            "garden-reference.jpg",
            "garage-gable-reference.jpg",
            "side-gable-reference.jpg",
        ):
            asset = ROOT / "static" / "textures" / "house" / filename
            self.assertTrue(asset.exists())
            self.assertLess(asset.stat().st_size, 1_500_000)
        self.assertIn("FDS-KS-800", script)
        self.assertNotIn(".house-stage.is-interacting .house-scene-label", stylesheet)

    def test_vehicle_assets_are_web_optimized_and_attributed(self) -> None:
        dashboard = (ROOT / "templates" / "index.html").read_text(encoding="utf-8")
        attributions = (ROOT / "static" / "models" / "ATTRIBUTIONS.md").read_text(encoding="utf-8")

        for filename in ("audi-q3.glb", "skoda-yeti.glb", "vw-fox.glb", "skoda-karoq.glb"):
            asset = ROOT / "static" / "models" / filename
            self.assertTrue(asset.exists())
            self.assertLess(asset.stat().st_size, 2_000_000)

        self.assertIn("2023 Audi Q3 40 TFSI", dashboard)
        self.assertIn("Ddiaz Design", dashboard)
        self.assertIn("2019 Skoda Karoq", dashboard)
        self.assertIn("BHP3D", attributions)
        self.assertIn("CC BY-NC-SA 4.0", attributions)


if __name__ == "__main__":
    unittest.main()
